trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false


- script: 'curl -sSL https://download.sourceclear.com/ci.sh | sh'
  displayName: 'CMD - Source Clear'
  env:
    SRCCLR_API_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY3Mjc5LCJleHAiOjE1OTYxMzc1NTYsImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiI3YTA1Y2E4Zi04NWIwLTQ5ZjQtODg3MS01OThhNGE0MzgzYjgiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.GmbYJaf1xcfk5XqjeY461pROsjBy4bCeR6PzHe92HArVzjc4XL9otCQxB6_x4pY0hIMdTsBlzDlmEj1NOPsDiHF8f5Aol4dQaSjH-aCmaTFhQcmhoV17f0-DfO55Do_2u_SzNdU66WpC9CiiadXtCE_cZiOTpbBVQhEHo6Lfv7U

- task: WhiteSource Bolt@20
  displayName: 'Whitesource bolt'
  inputs:
    advance: true

- task: WhiteSource@20
  displayName: 'Whitesource API'
  inputs:
    cwd: '$(Build.SourcesDirectory)'
    extensions: '**/*.*'
    productName: 'AIA_SG_Evaluation_2'
    projectName: 'node-express-azure'
    forceCheckAllDependencies: true
    forceUpdate: true
    WhiteSourceService: 'Whitesource connector'


- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  
